#!/usr/bin/env python3
"""Fold web/ into one self-contained .html file that anyone can open.

The app was already zero-dependency and zero-network — system fonts, no images,
no CDN — so "shareable" is purely a matter of inlining the three stylesheets and
the five scripts in the order the page already loads them. Nothing about the UI
or the behaviour changes; the same app.js runs, just from a <script> block
instead of a <script src>.

What DOES change, by itself and correctly, is the two places that ask the host
for something: app.js checks `window.webkit.messageHandlers.app` once, finds
nothing, and falls back to a Blob download for CSV and to window.print() for
printing — both of which are the better path in a browser anyway.

Usage: bundle.py <web dir> <output.html>
"""

import io
import os
import re
import sys


def guard(text, kind):
    """Neutralise a sequence that would close the element we are inlining into.

    An HTML parser ends a <script> at the first `</script`, wherever it appears —
    inside a string, inside a comment, it does not care. ui.js has exactly one,
    in a comment showing the theme-boot snippet. Escaping the slash keeps the
    text readable and stops it terminating the block.
    """
    if kind == "script":
        return re.sub(r"</(script)", r"<\\/\1", text, flags=re.I)
    return re.sub(r"</(style)", r"<\\/\1", text, flags=re.I)


def main():
    if len(sys.argv) < 3:
        print("usage: bundle.py <web dir> <output.html>", file=sys.stderr)
        return 2
    web, out = sys.argv[1], sys.argv[2]

    def read(name):
        with io.open(os.path.join(web, name), encoding="utf-8") as f:
            return f.read()

    html = read("index.html")

    # Order is the contract, not a detail: tokens before components before app,
    # and motion before ui before select-menu before model before app. Replacing each tag in
    # place preserves it without the bundler needing to know it.
    for name in ("tokens.css", "components.css", "app.css"):
        tag = '<link rel="stylesheet" href="%s">' % name
        if tag not in html:
            print("missing stylesheet link: %s" % name, file=sys.stderr)
            return 1
        html = html.replace(
            tag,
            "<style>\n/* ===== %s ===== */\n%s\n</style>" % (name, guard(read(name), "style")),
            1,
        )

    for name in ("motion.js", "ui.js", "select-menu.js", "model.js", "app.js"):
        tag = '<script src="%s"></script>' % name
        if tag not in html:
            print("missing script tag: %s" % name, file=sys.stderr)
            return 1
        html = html.replace(
            tag,
            "<script>\n/* ===== %s ===== */\n%s\n</script>" % (name, guard(read(name), "script")),
            1,
        )

    # Anything still pointing outside this file would defeat the whole exercise.
    # Markup is scanned with the inlined <script> and <style> bodies cut out (app.js
    # assigns `a.href = url` to a Blob URL, which is not a reference, and a CSS
    # selector like a[href="x"] is not one either); CSS is scanned inside <style>
    # blocks and style="" attributes. Case-insensitive throughout.
    I = re.I | re.S
    markup = re.sub(r"<script\b[^>]*>.*?</script>", "", html, flags=I)
    styles = "".join(re.findall(r"<style\b[^>]*>(.*?)</style>", markup, flags=I))
    markup = re.sub(r"<style\b[^>]*>.*?</style>", "", markup, flags=I)
    styles += " ".join(a or b for a, b in re.findall(r'\bstyle\s*=\s*(?:"([^"]*)"|\'([^\']*)\')', markup, flags=I))
    attr = r'\b(?:src|href|xlink:href|poster|data|action|formaction|srcset)\s*=\s*(?:"([^"]*)"|\'([^\']*)\'|([^\s>"\']+))'
    refs = [a or b or c for a, b, c in re.findall(attr, markup, flags=I)]
    # srcset holds "url 2x, url 3x"; meta refresh holds "5; url=..."
    refs = [u.strip().split()[0] if u.strip() else u for r in refs for u in r.split(",")]
    refs += re.findall(r'http-equiv\s*=\s*["\']?refresh[^>]*url\s*=\s*([^"\'>\s]+)', markup, flags=I)
    refs += re.findall(r'url\(\s*["\']?([^)"\']+)', styles, flags=I)
    refs += re.findall(r'@import\s+(?:url\()?\s*["\']?([^"\')\s;]+)', styles, flags=I)
    refs += re.findall(r'image-set\(\s*["\']([^"\']+)', styles, flags=I)
    from urllib.parse import unquote
    refs = [unquote(u) for u in refs]
    external = [u for u in refs if u and not u.startswith(("#", "data:"))]
    if external:
        print("refusing to write: still references %s" % ", ".join(sorted(set(external))), file=sys.stderr)
        return 1

    banner = (
        "<!--\n"
        "  Generated by tools/bundle.py — do not edit this file directly.\n"
        "  Edit web/ and rebuild. Everything is inlined: no network, no fonts to\n"
        "  load, no build step. Open it in any modern browser, or send it to\n"
        "  someone and they can too. Settings are remembered per browser.\n"
        "-->\n"
    )
    html = html.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + banner, 1)

    with io.open(out, "w", encoding="utf-8") as f:
        f.write(html)
    print("wrote %s (%.0f KB)" % (out, os.path.getsize(out) / 1024.0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
